### ISSUE TITLE
CIDR描述错误

### ISSUE THREAD

**Issue by sparrowhe** [tmplink/ipv6#4]
https://github.com/tmplink/ipv6/blob/main/SUBNET.md#cidr%E6%97%A0%E7%B1%BB%E5%88%AB%E5%9F%9F%E9%97%B4%E8%B7%AF%E7%94%B1

![image](https://user-images.githubusercontent.com/26871028/183249724-eb0352e9-f252-46d8-b315-b00873e05331.png)

**Comment by tmplink** [comment]
是的，这是预留的一个描述错误，终于被小天才发现了！
欢迎提交 pr。
